apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location
  template:
    metadata:
      labels:
        app: location
    spec:
      containers:
        - image: pockar/location:latest
          name: location
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://balarama.db.elephantsql.com:5432/iyljirkx
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: iyljirkx
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: hzSKsxl3Qdm76cFMC3OqHyH8xTvwrb3J
              valueFrom: #use Kubernetes secret for storing the password
               # secretKeyRef: 
                ## key: #to be added
          ports:
            - containerPort: 8085
              name: server

---

apiVersion: v1
kind: Service
metadata:
  name: location
spec:
  type: ClusterIP
  ports:
    - port: 8085
      protocol: TCP
      targetPort: server
  selector:
    app: location
